# Generated by Django 3.1.6 on 2021-02-03 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0002_auto_20210203_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='drinks',
        ),
        migrations.AddField(
            model_name='pizza',
            name='drinks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pizzas.drink'),
        ),
    ]
