# Generated by Django 3.1.6 on 2021-02-03 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20210203_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='drinks',
            new_name='drink',
        ),
    ]
